/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated.tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedIntegrationRouteImport } from './routes/_authenticated.integration'
import { Route as AuthenticatedTeachersIndexRouteImport } from './routes/_authenticated.teachers.index'
import { Route as AuthenticatedStudentsIndexRouteImport } from './routes/_authenticated.students.index'
import { Route as AuthenticatedScheduleIndexRouteImport } from './routes/_authenticated.schedule.index'
import { Route as AuthenticatedSalariesIndexRouteImport } from './routes/_authenticated.salaries.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated.reports.index'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated.leads.index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated.groups.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated.finance.index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated.courses.index'
import { Route as AuthenticatedAttendanceIndexRouteImport } from './routes/_authenticated.attendance.index'
import { Route as AuthenticatedStudentsIdRouteImport } from './routes/_authenticated.students.$id'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated.leads.$id'
import { Route as AuthenticatedMeStudentsIndexRouteImport } from './routes/_authenticated.me.students.index'
import { Route as AuthenticatedMeGroupsIndexRouteImport } from './routes/_authenticated.me.groups.index'
import { Route as AuthenticatedMeAttendanceIndexRouteImport } from './routes/_authenticated.me.attendance.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationRoute =
  AuthenticatedIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeachersIndexRoute =
  AuthenticatedTeachersIndexRouteImport.update({
    id: '/teachers/',
    path: '/teachers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsIndexRoute =
  AuthenticatedStudentsIndexRouteImport.update({
    id: '/students/',
    path: '/students/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScheduleIndexRoute =
  AuthenticatedScheduleIndexRouteImport.update({
    id: '/schedule/',
    path: '/schedule/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalariesIndexRoute =
  AuthenticatedSalariesIndexRouteImport.update({
    id: '/salaries/',
    path: '/salaries/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAttendanceIndexRoute =
  AuthenticatedAttendanceIndexRouteImport.update({
    id: '/attendance/',
    path: '/attendance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentsIdRoute = AuthenticatedStudentsIdRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeStudentsIndexRoute =
  AuthenticatedMeStudentsIndexRouteImport.update({
    id: '/me/students/',
    path: '/me/students/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeGroupsIndexRoute =
  AuthenticatedMeGroupsIndexRouteImport.update({
    id: '/me/groups/',
    path: '/me/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeAttendanceIndexRoute =
  AuthenticatedMeAttendanceIndexRouteImport.update({
    id: '/me/attendance/',
    path: '/me/attendance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/courses/': typeof AuthenticatedCoursesIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/salaries/': typeof AuthenticatedSalariesIndexRoute
  '/schedule/': typeof AuthenticatedScheduleIndexRoute
  '/students/': typeof AuthenticatedStudentsIndexRoute
  '/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/me/attendance/': typeof AuthenticatedMeAttendanceIndexRoute
  '/me/groups/': typeof AuthenticatedMeGroupsIndexRoute
  '/me/students/': typeof AuthenticatedMeStudentsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/': typeof AuthenticatedIndexRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/students/$id': typeof AuthenticatedStudentsIdRoute
  '/attendance': typeof AuthenticatedAttendanceIndexRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/salaries': typeof AuthenticatedSalariesIndexRoute
  '/schedule': typeof AuthenticatedScheduleIndexRoute
  '/students': typeof AuthenticatedStudentsIndexRoute
  '/teachers': typeof AuthenticatedTeachersIndexRoute
  '/me/attendance': typeof AuthenticatedMeAttendanceIndexRoute
  '/me/groups': typeof AuthenticatedMeGroupsIndexRoute
  '/me/students': typeof AuthenticatedMeStudentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/integration': typeof AuthenticatedIntegrationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/students/$id': typeof AuthenticatedStudentsIdRoute
  '/_authenticated/attendance/': typeof AuthenticatedAttendanceIndexRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/salaries/': typeof AuthenticatedSalariesIndexRoute
  '/_authenticated/schedule/': typeof AuthenticatedScheduleIndexRoute
  '/_authenticated/students/': typeof AuthenticatedStudentsIndexRoute
  '/_authenticated/teachers/': typeof AuthenticatedTeachersIndexRoute
  '/_authenticated/me/attendance/': typeof AuthenticatedMeAttendanceIndexRoute
  '/_authenticated/me/groups/': typeof AuthenticatedMeGroupsIndexRoute
  '/_authenticated/me/students/': typeof AuthenticatedMeStudentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/integration'
    | '/settings'
    | '/tasks'
    | '/leads/$id'
    | '/students/$id'
    | '/attendance/'
    | '/courses/'
    | '/finance/'
    | '/groups/'
    | '/leads/'
    | '/reports/'
    | '/salaries/'
    | '/schedule/'
    | '/students/'
    | '/teachers/'
    | '/me/attendance/'
    | '/me/groups/'
    | '/me/students/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/integration'
    | '/settings'
    | '/tasks'
    | '/'
    | '/leads/$id'
    | '/students/$id'
    | '/attendance'
    | '/courses'
    | '/finance'
    | '/groups'
    | '/leads'
    | '/reports'
    | '/salaries'
    | '/schedule'
    | '/students'
    | '/teachers'
    | '/me/attendance'
    | '/me/groups'
    | '/me/students'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/integration'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/'
    | '/_authenticated/leads/$id'
    | '/_authenticated/students/$id'
    | '/_authenticated/attendance/'
    | '/_authenticated/courses/'
    | '/_authenticated/finance/'
    | '/_authenticated/groups/'
    | '/_authenticated/leads/'
    | '/_authenticated/reports/'
    | '/_authenticated/salaries/'
    | '/_authenticated/schedule/'
    | '/_authenticated/students/'
    | '/_authenticated/teachers/'
    | '/_authenticated/me/attendance/'
    | '/_authenticated/me/groups/'
    | '/_authenticated/me/students/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integration': {
      id: '/_authenticated/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AuthenticatedIntegrationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teachers/': {
      id: '/_authenticated/teachers/'
      path: '/teachers'
      fullPath: '/teachers/'
      preLoaderRoute: typeof AuthenticatedTeachersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/': {
      id: '/_authenticated/students/'
      path: '/students'
      fullPath: '/students/'
      preLoaderRoute: typeof AuthenticatedStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule/': {
      id: '/_authenticated/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof AuthenticatedScheduleIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/salaries/': {
      id: '/_authenticated/salaries/'
      path: '/salaries'
      fullPath: '/salaries/'
      preLoaderRoute: typeof AuthenticatedSalariesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/attendance/': {
      id: '/_authenticated/attendance/'
      path: '/attendance'
      fullPath: '/attendance/'
      preLoaderRoute: typeof AuthenticatedAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students/$id': {
      id: '/_authenticated/students/$id'
      path: '/students/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof AuthenticatedStudentsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/students/': {
      id: '/_authenticated/me/students/'
      path: '/me/students'
      fullPath: '/me/students/'
      preLoaderRoute: typeof AuthenticatedMeStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/groups/': {
      id: '/_authenticated/me/groups/'
      path: '/me/groups'
      fullPath: '/me/groups/'
      preLoaderRoute: typeof AuthenticatedMeGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/attendance/': {
      id: '/_authenticated/me/attendance/'
      path: '/me/attendance'
      fullPath: '/me/attendance/'
      preLoaderRoute: typeof AuthenticatedMeAttendanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIntegrationRoute: typeof AuthenticatedIntegrationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedStudentsIdRoute: typeof AuthenticatedStudentsIdRoute
  AuthenticatedAttendanceIndexRoute: typeof AuthenticatedAttendanceIndexRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSalariesIndexRoute: typeof AuthenticatedSalariesIndexRoute
  AuthenticatedScheduleIndexRoute: typeof AuthenticatedScheduleIndexRoute
  AuthenticatedStudentsIndexRoute: typeof AuthenticatedStudentsIndexRoute
  AuthenticatedTeachersIndexRoute: typeof AuthenticatedTeachersIndexRoute
  AuthenticatedMeAttendanceIndexRoute: typeof AuthenticatedMeAttendanceIndexRoute
  AuthenticatedMeGroupsIndexRoute: typeof AuthenticatedMeGroupsIndexRoute
  AuthenticatedMeStudentsIndexRoute: typeof AuthenticatedMeStudentsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIntegrationRoute: AuthenticatedIntegrationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedStudentsIdRoute: AuthenticatedStudentsIdRoute,
  AuthenticatedAttendanceIndexRoute: AuthenticatedAttendanceIndexRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSalariesIndexRoute: AuthenticatedSalariesIndexRoute,
  AuthenticatedScheduleIndexRoute: AuthenticatedScheduleIndexRoute,
  AuthenticatedStudentsIndexRoute: AuthenticatedStudentsIndexRoute,
  AuthenticatedTeachersIndexRoute: AuthenticatedTeachersIndexRoute,
  AuthenticatedMeAttendanceIndexRoute: AuthenticatedMeAttendanceIndexRoute,
  AuthenticatedMeGroupsIndexRoute: AuthenticatedMeGroupsIndexRoute,
  AuthenticatedMeStudentsIndexRoute: AuthenticatedMeStudentsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
